# Generated by Django 4.2.3 on 2023-07-30 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('session', '0002_remove_usersession_sessions_created_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserSession',
        ),
    ]
