# Generated by Django 4.2.3 on 2023-07-30 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('session', '0005_rename_username_usersession_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='SessionsCreated',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(max_length=6, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='usersession',
            name='sessions_created',
            field=models.ManyToManyField(blank=True, to='session.sessionscreated'),
        ),
    ]
