# Generated by Django 4.2.3 on 2023-07-30 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('session', '0006_sessionscreated_alter_usersession_sessions_created'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usersession',
            name='sessions_created',
        ),
    ]
