# Generated by Django 3.2.20 on 2023-07-13 09:24

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('authentication', '0003_auto_20230713_1453'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='users_answered',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
