# Generated by Django 3.2.20 on 2023-07-13 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_choice_vote'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='users_answered',
        ),
        migrations.DeleteModel(
            name='Choice',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
    ]
