# Generated by Django 3.2.20 on 2023-07-23 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poller', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='session_id',
            field=models.CharField(default='ADMIN01', max_length=10, null=True),
        ),
    ]
